[phases.setup]
nixPkgs = ['php82', 'php82Extensions.pdo', 'php82Extensions.pdo_mysql', 'php82Extensions.mbstring', 'php82Extensions.xml', 'php82Extensions.curl', 'php82Extensions.gd', 'php82Extensions.zip', 'php82Extensions.tokenizer', 'php82Extensions.openssl', 'composer']

[phases.install]
cmds = [
  'COMPOSER_ALLOW_SUPERUSER=1 composer install --no-dev --optimize-autoloader --ignore-platform-reqs'
]

[phases.build]
cmds = [
  'mkdir -p bootstrap/cache storage/framework/sessions storage/framework/views storage/framework/cache storage/logs storage/app/public',
  'chmod -R 775 storage bootstrap/cache',
  'php artisan package:discover --ansi'
]

[start]
cmd = 'bash start.sh'
